namespace HexaEngine.Editor.NodeEditor
{
    public enum PinType
    {
        Flow,
        Bool,
        Int,
        Float,
        Vector2,
        Vector3,
        Vector4,
        String,
        Object,
        Function,
        Delegate,
        TextureAny,
        Texture1D,
        Texture1DArray,
        Texture2D,
        Texture2DMS,
        Texture2DArray,
        Texture2DMSArray,
        TextureCube,
        TextureCubeArray,
        Texture3D,
        Vertices,
        Buffer,
        Sampler,
    }
}