namespace HexaEngine.Core.Graphics.Reflection
{
    public enum Primitive
    {
        Undefined = 0,
        Point = 1,
        Line = 2,
        Triangle = 3,
        LineAdj = 6,
        TriangleAdj = 7,
        PatchListWith1ControlPoint = 8,
        PatchListWith2ControlPoint = 9,
        PatchListWith3ControlPoint = 10,
        PatchListWith4ControlPoint = 11,
        PatchListWith5ControlPoint = 12,
        PatchListWith6ControlPoint = 13,
        PatchListWith7ControlPoint = 14,
        PatchListWith8ControlPoint = 0xF,
        PatchListWith9ControlPoint = 0x10,
        PatchListWith10ControlPoint = 17,
        PatchListWith11ControlPoint = 18,
        PatchListWith12ControlPoint = 19,
        PatchListWith13ControlPoint = 20,
        PatchListWith14ControlPoint = 21,
        PatchListWith15ControlPoint = 22,
        PatchListWith16ControlPoint = 23,
        PatchListWith17ControlPoint = 24,
        PatchListWith18ControlPoint = 25,
        PatchListWith19ControlPoint = 26,
        PatchListWith20ControlPoint = 27,
        PatchListWith21ControlPoint = 28,
        PatchListWith22ControlPoint = 29,
        PatchListWith23ControlPoint = 30,
        PatchListWith24ControlPoint = 0x1F,
        PatchListWith25ControlPoint = 0x20,
        PatchListWith26ControlPoint = 33,
        PatchListWith27ControlPoint = 34,
        PatchListWith28ControlPoint = 35,
        PatchListWith29ControlPoint = 36,
        PatchListWith30ControlPoint = 37,
        PatchListWith31ControlPoint = 38,
        PatchListWith32ControlPoint = 39,
    }
}