namespace HexaEngine.SPIRVCross
{
    public enum SpvSourceLanguage
    {
        Unknown = 0,
        ESSL = 1,
        GLSL = 2,
        OpenCLC = 3,
        OpenCLCPP = 4,
        HLSL = 5,
        Max = 2147483647,
    }

    public enum SpvExecutionModel
    {
        Vertex = 0,
        TessellationControl = 1,
        TessellationEvaluation = 2,
        Geometry = 3,
        Fragment = 4,
        GLCompute = 5,
        Kernel = 6,
        TaskNV = 5267,
        MeshNV = 5268,
        RayGenerationKHR = 5313,
        RayGenerationNV = 5313,
        IntersectionKHR = 5314,
        IntersectionNV = 5314,
        AnyHitKHR = 5315,
        AnyHitNV = 5315,
        ClosestHitKHR = 5316,
        ClosestHitNV = 5316,
        MissKHR = 5317,
        MissNV = 5317,
        CallableKHR = 5318,
        CallableNV = 5318,
        Max = 2147483647,
    }

    public enum SpvAddressingModel
    {
        Logical = 0,
        Physical32 = 1,
        Physical64 = 2,
        PhysicalStorageBuffer64 = 5348,
        PhysicalStorageBuffer64EXT = 5348,
        Max = 2147483647,
    }

    public enum SpvMemoryModel
    {
        Simple = 0,
        GLSL450 = 1,
        OpenCL = 2,
        Vulkan = 3,
        VulkanKHR = 3,
        Max = 2147483647,
    }

    public enum SpvExecutionMode
    {
        Invocations = 0,
        SpacingEqual = 1,
        SpacingFractionalEven = 2,
        SpacingFractionalOdd = 3,
        VertexOrderCw = 4,
        VertexOrderCcw = 5,
        PixelCenterInteger = 6,
        OriginUpperLeft = 7,
        OriginLowerLeft = 8,
        EarlyFragmentTests = 9,
        PointMode = 10,
        Xfb = 11,
        DepthReplacing = 12,
        DepthGreater = 14,
        DepthLess = 15,
        DepthUnchanged = 16,
        LocalSize = 17,
        LocalSizeHint = 18,
        InputPoints = 19,
        InputLines = 20,
        InputLinesAdjacency = 21,
        Triangles = 22,
        InputTrianglesAdjacency = 23,
        Quads = 24,
        Isolines = 25,
        OutputVertices = 26,
        OutputPoints = 27,
        OutputLineStrip = 28,
        OutputTriangleStrip = 29,
        VecTypeHint = 30,
        ContractionOff = 31,
        Initializer = 33,
        Finalizer = 34,
        SubgroupSize = 35,
        SubgroupsPerWorkgroup = 36,
        SubgroupsPerWorkgroupId = 37,
        LocalSizeId = 38,
        LocalSizeHintId = 39,
        PostDepthCoverage = 4446,
        DenormPreserve = 4459,
        DenormFlushToZero = 4460,
        SignedZeroInfNanPreserve = 4461,
        RoundingModeRTE = 4462,
        RoundingModeRTZ = 4463,
        StencilRefReplacingEXT = 5027,
        OutputLinesNV = 5269,
        OutputPrimitivesNV = 5270,
        DerivativeGroupQuadsNV = 5289,
        DerivativeGroupLinearNV = 5290,
        OutputTrianglesNV = 5298,
        PixelInterlockOrderedEXT = 5366,
        PixelInterlockUnorderedEXT = 5367,
        SampleInterlockOrderedEXT = 5368,
        SampleInterlockUnorderedEXT = 5369,
        ShadingRateInterlockOrderedEXT = 5370,
        ShadingRateInterlockUnorderedEXT = 5371,
        MaxWorkgroupSizeINTEL = 5893,
        MaxWorkDimINTEL = 5894,
        NoGlobalOffsetINTEL = 5895,
        NumSIMDWorkitemsINTEL = 5896,
        Max = 2147483647,
    }

    public enum SpvStorageClass
    {
        UniformConstant = 0,
        Input = 1,
        Uniform = 2,
        Output = 3,
        Workgroup = 4,
        CrossWorkgroup = 5,
        Private = 6,
        Function = 7,
        Generic = 8,
        PushConstant = 9,
        AtomicCounter = 10,
        Image = 11,
        StorageBuffer = 12,
        CallableDataKHR = 5328,
        CallableDataNV = 5328,
        IncomingCallableDataKHR = 5329,
        IncomingCallableDataNV = 5329,
        RayPayloadKHR = 5338,
        RayPayloadNV = 5338,
        HitAttributeKHR = 5339,
        HitAttributeNV = 5339,
        IncomingRayPayloadKHR = 5342,
        IncomingRayPayloadNV = 5342,
        ShaderRecordBufferKHR = 5343,
        ShaderRecordBufferNV = 5343,
        PhysicalStorageBuffer = 5349,
        PhysicalStorageBufferEXT = 5349,
        CodeSectionINTEL = 5605,
        Max = 2147483647,
    }

    public enum SpvDim
    {
        Dim1D = 0,
        Dim2D = 1,
        Dim3D = 2,
        Cube = 3,
        Rect = 4,
        Buffer = 5,
        SubpassData = 6,
        Max = 2147483647,
    }

    public enum SpvSamplerAddressingMode
    {
        None = 0,
        ClampToEdge = 1,
        Clamp = 2,
        Repeat = 3,
        RepeatMirrored = 4,
        Max = 2147483647,
    }

    public enum SpvSamplerFilterMode
    {
        Nearest = 0,
        Linear = 1,
        Max = 2147483647,
    }

    public enum SpvImageFormat
    {
        Unknown = 0,
        Rgba32f = 1,
        Rgba16f = 2,
        R32f = 3,
        Rgba8 = 4,
        Rgba8Snorm = 5,
        Rg32f = 6,
        Rg16f = 7,
        R11fG11fB10f = 8,
        R16f = 9,
        Rgba16 = 10,
        Rgb10A2 = 11,
        Rg16 = 12,
        Rg8 = 13,
        R16 = 14,
        R8 = 15,
        Rgba16Snorm = 16,
        Rg16Snorm = 17,
        Rg8Snorm = 18,
        R16Snorm = 19,
        R8Snorm = 20,
        Rgba32i = 21,
        Rgba16i = 22,
        Rgba8i = 23,
        R32i = 24,
        Rg32i = 25,
        Rg16i = 26,
        Rg8i = 27,
        R16i = 28,
        R8i = 29,
        Rgba32ui = 30,
        Rgba16ui = 31,
        Rgba8ui = 32,
        R32ui = 33,
        Rgb10a2ui = 34,
        Rg32ui = 35,
        Rg16ui = 36,
        Rg8ui = 37,
        R16ui = 38,
        R8ui = 39,
        R64ui = 40,
        R64i = 41,
        Max = 2147483647,
    }

    public enum SpvImageChannelOrder
    {
        R = 0,
        A = 1,
        RG = 2,
        RA = 3,
        RGB = 4,
        RGBA = 5,
        BGRA = 6,
        ARGB = 7,
        Intensity = 8,
        Luminance = 9,
        Rx = 10,
        RGx = 11,
        RGBx = 12,
        Depth = 13,
        DepthStencil = 14,
        sRGB = 15,
        sRGBx = 16,
        sRGBA = 17,
        sBGRA = 18,
        ABGR = 19,
        Max = 2147483647,
    }

    public enum SpvImageChannelDataType
    {
        SnormInt8 = 0,
        SnormInt16 = 1,
        UnormInt8 = 2,
        UnormInt16 = 3,
        UnormShort565 = 4,
        UnormShort555 = 5,
        UnormInt101010 = 6,
        SignedInt8 = 7,
        SignedInt16 = 8,
        SignedInt32 = 9,
        UnsignedInt8 = 10,
        UnsignedInt16 = 11,
        UnsignedInt32 = 12,
        HalfFloat = 13,
        Float = 14,
        UnormInt24 = 15,
        UnormInt1010102 = 16,
        Max = 2147483647,
    }

    public enum SpvImageOperandsShift
    {
        BiasShift = 0,
        LodShift = 1,
        GradShift = 2,
        ConstOffsetShift = 3,
        OffsetShift = 4,
        ConstOffsetsShift = 5,
        SampleShift = 6,
        MinLodShift = 7,
        MakeTexelAvailableShift = 8,
        MakeTexelAvailableKHRShift = 8,
        MakeTexelVisibleShift = 9,
        MakeTexelVisibleKHRShift = 9,
        NonPrivateTexelShift = 10,
        NonPrivateTexelKHRShift = 10,
        VolatileTexelShift = 11,
        VolatileTexelKHRShift = 11,
        SignExtendShift = 12,
        ZeroExtendShift = 13,
        Max = 2147483647,
    }

    public enum SpvImageOperandsMask
    {
        None = 0,
        BiasMask = 1,
        LodMask = 2,
        GradMask = 4,
        ConstOffsetMask = 8,
        OffsetMask = 16,
        ConstOffsetsMask = 32,
        SampleMask = 64,
        MinLodMask = 128,
        MakeTexelAvailableMask = 256,
        MakeTexelAvailableKHRMask = 256,
        MakeTexelVisibleMask = 512,
        MakeTexelVisibleKHRMask = 512,
        NonPrivateTexelMask = 1024,
        NonPrivateTexelKHRMask = 1024,
        VolatileTexelMask = 2048,
        VolatileTexelKHRMask = 2048,
        SignExtendMask = 4096,
        ZeroExtendMask = 8192,
    }

    public enum SpvFPFastMathModeShift
    {
        NotNaNShift = 0,
        NotInfShift = 1,
        NSZShift = 2,
        AllowRecipShift = 3,
        FastShift = 4,
        Max = 2147483647,
    }

    public enum SpvFPFastMathModeMask
    {
        None = 0,
        NotNaNMask = 1,
        NotInfMask = 2,
        NSZMask = 4,
        AllowRecipMask = 8,
        FastMask = 16,
    }

    public enum SpvFPRoundingMode
    {
        RTE = 0,
        RTZ = 1,
        RTP = 2,
        RTN = 3,
        Max = 2147483647,
    }

    public enum SpvLinkageType
    {
        Export = 0,
        Import = 1,
        Max = 2147483647,
    }

    public enum SpvAccessQualifier
    {
        ReadOnly = 0,
        WriteOnly = 1,
        ReadWrite = 2,
        Max = 2147483647,
    }

    public enum SpvFunctionParameterAttribute
    {
        Zext = 0,
        Sext = 1,
        ByVal = 2,
        Sret = 3,
        NoAlias = 4,
        NoCapture = 5,
        NoWrite = 6,
        NoReadWrite = 7,
        Max = 2147483647,
    }

    public enum SpvDecoration
    {
        RelaxedPrecision = 0,
        SpecId = 1,
        Block = 2,
        BufferBlock = 3,
        RowMajor = 4,
        ColMajor = 5,
        ArrayStride = 6,
        MatrixStride = 7,
        GLSLShared = 8,
        GLSLPacked = 9,
        CPacked = 10,
        BuiltIn = 11,
        NoPerspective = 13,
        Flat = 14,
        Patch = 15,
        Centroid = 16,
        Sample = 17,
        Invariant = 18,
        Restrict = 19,
        Aliased = 20,
        Volatile = 21,
        Constant = 22,
        Coherent = 23,
        NonWritable = 24,
        NonReadable = 25,
        Uniform = 26,
        UniformId = 27,
        SaturatedConversion = 28,
        Stream = 29,
        Location = 30,
        Component = 31,
        Index = 32,
        Binding = 33,
        DescriptorSet = 34,
        Offset = 35,
        XfbBuffer = 36,
        XfbStride = 37,
        FuncParamAttr = 38,
        FPRoundingMode = 39,
        FPFastMathMode = 40,
        LinkageAttributes = 41,
        NoContraction = 42,
        InputAttachmentIndex = 43,
        Alignment = 44,
        MaxByteOffset = 45,
        AlignmentId = 46,
        MaxByteOffsetId = 47,
        NoSignedWrap = 4469,
        NoUnsignedWrap = 4470,
        ExplicitInterpAMD = 4999,
        OverrideCoverageNV = 5248,
        PassthroughNV = 5250,
        ViewportRelativeNV = 5252,
        SecondaryViewportRelativeNV = 5256,
        PerPrimitiveNV = 5271,
        PerViewNV = 5272,
        PerTaskNV = 5273,
        PerVertexNV = 5285,
        NonUniform = 5300,
        NonUniformEXT = 5300,
        RestrictPointer = 5355,
        RestrictPointerEXT = 5355,
        AliasedPointer = 5356,
        AliasedPointerEXT = 5356,
        ReferencedIndirectlyINTEL = 5602,
        CounterBuffer = 5634,
        HlslCounterBufferGOOGLE = 5634,
        HlslSemanticGOOGLE = 5635,
        UserSemantic = 5635,
        UserTypeGOOGLE = 5636,
        RegisterINTEL = 5825,
        MemoryINTEL = 5826,
        NumbanksINTEL = 5827,
        BankwidthINTEL = 5828,
        MaxPrivateCopiesINTEL = 5829,
        SinglepumpINTEL = 5830,
        DoublepumpINTEL = 5831,
        MaxReplicatesINTEL = 5832,
        SimpleDualPortINTEL = 5833,
        MergeINTEL = 5834,
        BankBitsINTEL = 5835,
        ForcePow2DepthINTEL = 5836,
        Max = 2147483647,
    }

    public enum SpvBuiltIn
    {
        Position = 0,
        PointSize = 1,
        ClipDistance = 3,
        CullDistance = 4,
        VertexId = 5,
        InstanceId = 6,
        PrimitiveId = 7,
        InvocationId = 8,
        Layer = 9,
        ViewportIndex = 10,
        TessLevelOuter = 11,
        TessLevelInner = 12,
        TessCoord = 13,
        PatchVertices = 14,
        FragCoord = 15,
        PointCoord = 16,
        FrontFacing = 17,
        SampleId = 18,
        SamplePosition = 19,
        SampleMask = 20,
        FragDepth = 22,
        HelperInvocation = 23,
        NumWorkgroups = 24,
        WorkgroupSize = 25,
        WorkgroupId = 26,
        LocalInvocationId = 27,
        GlobalInvocationId = 28,
        LocalInvocationIndex = 29,
        WorkDim = 30,
        GlobalSize = 31,
        EnqueuedWorkgroupSize = 32,
        GlobalOffset = 33,
        GlobalLinearId = 34,
        SubgroupSize = 36,
        SubgroupMaxSize = 37,
        NumSubgroups = 38,
        NumEnqueuedSubgroups = 39,
        SubgroupId = 40,
        SubgroupLocalInvocationId = 41,
        VertexIndex = 42,
        InstanceIndex = 43,
        SubgroupEqMask = 4416,
        SubgroupEqMaskKHR = 4416,
        SubgroupGeMask = 4417,
        SubgroupGeMaskKHR = 4417,
        SubgroupGtMask = 4418,
        SubgroupGtMaskKHR = 4418,
        SubgroupLeMask = 4419,
        SubgroupLeMaskKHR = 4419,
        SubgroupLtMask = 4420,
        SubgroupLtMaskKHR = 4420,
        BaseVertex = 4424,
        BaseInstance = 4425,
        DrawIndex = 4426,
        PrimitiveShadingRateKHR = 4432,
        DeviceIndex = 4438,
        ViewIndex = 4440,
        ShadingRateKHR = 4444,
        BaryCoordNoPerspAMD = 4992,
        BaryCoordNoPerspCentroidAMD = 4993,
        BaryCoordNoPerspSampleAMD = 4994,
        BaryCoordSmoothAMD = 4995,
        BaryCoordSmoothCentroidAMD = 4996,
        BaryCoordSmoothSampleAMD = 4997,
        BaryCoordPullModelAMD = 4998,
        FragStencilRefEXT = 5014,
        ViewportMaskNV = 5253,
        SecondaryPositionNV = 5257,
        SecondaryViewportMaskNV = 5258,
        PositionPerViewNV = 5261,
        ViewportMaskPerViewNV = 5262,
        FullyCoveredEXT = 5264,
        TaskCountNV = 5274,
        PrimitiveCountNV = 5275,
        PrimitiveIndicesNV = 5276,
        ClipDistancePerViewNV = 5277,
        CullDistancePerViewNV = 5278,
        LayerPerViewNV = 5279,
        MeshViewCountNV = 5280,
        MeshViewIndicesNV = 5281,
        BaryCoordNV = 5286,
        BaryCoordNoPerspNV = 5287,
        FragSizeEXT = 5292,
        FragmentSizeNV = 5292,
        FragInvocationCountEXT = 5293,
        InvocationsPerPixelNV = 5293,
        LaunchIdKHR = 5319,
        LaunchIdNV = 5319,
        LaunchSizeKHR = 5320,
        LaunchSizeNV = 5320,
        WorldRayOriginKHR = 5321,
        WorldRayOriginNV = 5321,
        WorldRayDirectionKHR = 5322,
        WorldRayDirectionNV = 5322,
        ObjectRayOriginKHR = 5323,
        ObjectRayOriginNV = 5323,
        ObjectRayDirectionKHR = 5324,
        ObjectRayDirectionNV = 5324,
        RayTminKHR = 5325,
        RayTminNV = 5325,
        RayTmaxKHR = 5326,
        RayTmaxNV = 5326,
        InstanceCustomIndexKHR = 5327,
        InstanceCustomIndexNV = 5327,
        ObjectToWorldKHR = 5330,
        ObjectToWorldNV = 5330,
        WorldToObjectKHR = 5331,
        WorldToObjectNV = 5331,
        HitTNV = 5332,
        HitKindKHR = 5333,
        HitKindNV = 5333,
        IncomingRayFlagsKHR = 5351,
        IncomingRayFlagsNV = 5351,
        RayGeometryIndexKHR = 5352,
        WarpsPerSMNV = 5374,
        SMCountNV = 5375,
        WarpIDNV = 5376,
        SMIDNV = 5377,
        Max = 2147483647,
    }

    public enum SpvSelectionControlShift
    {
        FlattenShift = 0,
        DontFlattenShift = 1,
        Max = 2147483647,
    }

    public enum SpvSelectionControlMask
    {
        None = 0,
        FlattenMask = 1,
        DontFlattenMask = 2,
    }

    public enum SpvLoopControlShift
    {
        UnrollShift = 0,
        DontUnrollShift = 1,
        DependencyInfiniteShift = 2,
        DependencyLengthShift = 3,
        MinIterationsShift = 4,
        MaxIterationsShift = 5,
        IterationMultipleShift = 6,
        PeelCountShift = 7,
        PartialCountShift = 8,
        InitiationIntervalINTELShift = 16,
        MaxConcurrencyINTELShift = 17,
        DependencyArrayINTELShift = 18,
        PipelineEnableINTELShift = 19,
        LoopCoalesceINTELShift = 20,
        MaxInterleavingINTELShift = 21,
        SpeculatedIterationsINTELShift = 22,
        Max = 2147483647,
    }

    public enum SpvLoopControlMask
    {
        None = 0,
        UnrollMask = 1,
        DontUnrollMask = 2,
        DependencyInfiniteMask = 4,
        DependencyLengthMask = 8,
        MinIterationsMask = 16,
        MaxIterationsMask = 32,
        IterationMultipleMask = 64,
        PeelCountMask = 128,
        PartialCountMask = 256,
        InitiationIntervalINTELMask = 65536,
        MaxConcurrencyINTELMask = 131072,
        DependencyArrayINTELMask = 262144,
        PipelineEnableINTELMask = 524288,
        LoopCoalesceINTELMask = 1048576,
        MaxInterleavingINTELMask = 2097152,
        SpeculatedIterationsINTELMask = 4194304,
    }

    public enum SpvFunctionControlShift
    {
        InlineShift = 0,
        DontInlineShift = 1,
        PureShift = 2,
        ConstShift = 3,
        Max = 2147483647,
    }

    public enum SpvFunctionControlMask
    {
        None = 0,
        InlineMask = 1,
        DontInlineMask = 2,
        PureMask = 4,
        ConstMask = 8,
    }

    public enum SpvMemorySemanticsShift
    {
        AcquireShift = 1,
        ReleaseShift = 2,
        AcquireReleaseShift = 3,
        SequentiallyConsistentShift = 4,
        UniformMemoryShift = 6,
        SubgroupMemoryShift = 7,
        WorkgroupMemoryShift = 8,
        CrossWorkgroupMemoryShift = 9,
        AtomicCounterMemoryShift = 10,
        ImageMemoryShift = 11,
        OutputMemoryShift = 12,
        OutputMemoryKHRShift = 12,
        MakeAvailableShift = 13,
        MakeAvailableKHRShift = 13,
        MakeVisibleShift = 14,
        MakeVisibleKHRShift = 14,
        VolatileShift = 15,
        Max = 2147483647,
    }

    public enum SpvMemorySemanticsMask
    {
        None = 0,
        AcquireMask = 2,
        ReleaseMask = 4,
        AcquireReleaseMask = 8,
        SequentiallyConsistentMask = 16,
        UniformMemoryMask = 64,
        SubgroupMemoryMask = 128,
        WorkgroupMemoryMask = 256,
        CrossWorkgroupMemoryMask = 512,
        AtomicCounterMemoryMask = 1024,
        ImageMemoryMask = 2048,
        OutputMemoryMask = 4096,
        OutputMemoryKHRMask = 4096,
        MakeAvailableMask = 8192,
        MakeAvailableKHRMask = 8192,
        MakeVisibleMask = 16384,
        MakeVisibleKHRMask = 16384,
        VolatileMask = 32768,
    }

    public enum SpvMemoryAccessShift
    {
        VolatileShift = 0,
        AlignedShift = 1,
        NontemporalShift = 2,
        MakePointerAvailableShift = 3,
        MakePointerAvailableKHRShift = 3,
        MakePointerVisibleShift = 4,
        MakePointerVisibleKHRShift = 4,
        NonPrivatePointerShift = 5,
        NonPrivatePointerKHRShift = 5,
        Max = 2147483647,
    }

    public enum SpvMemoryAccessMask
    {
        None = 0,
        VolatileMask = 1,
        AlignedMask = 2,
        NontemporalMask = 4,
        MakePointerAvailableMask = 8,
        MakePointerAvailableKHRMask = 8,
        MakePointerVisibleMask = 16,
        MakePointerVisibleKHRMask = 16,
        NonPrivatePointerMask = 32,
        NonPrivatePointerKHRMask = 32,
    }

    public enum SpvScope
    {
        CrossDevice = 0,
        Device = 1,
        Workgroup = 2,
        Subgroup = 3,
        Invocation = 4,
        QueueFamily = 5,
        QueueFamilyKHR = 5,
        ShaderCallKHR = 6,
        Max = 2147483647,
    }

    public enum SpvGroupOperation
    {
        Reduce = 0,
        InclusiveScan = 1,
        ExclusiveScan = 2,
        ClusteredReduce = 3,
        PartitionedReduceNV = 6,
        PartitionedInclusiveScanNV = 7,
        PartitionedExclusiveScanNV = 8,
        Max = 2147483647,
    }

    public enum SpvKernelEnqueueFlags
    {
        NoWait = 0,
        WaitKernel = 1,
        WaitWorkGroup = 2,
        Max = 2147483647,
    }

    public enum SpvKernelProfilingInfoShift
    {
        CmdExecTimeShift = 0,
        Max = 2147483647,
    }

    public enum SpvKernelProfilingInfoMask
    {
        None = 0,
        CmdExecTimeMask = 1,
    }

    public enum SpvCapability
    {
        Matrix = 0,
        Shader = 1,
        Geometry = 2,
        Tessellation = 3,
        Addresses = 4,
        Linkage = 5,
        Kernel = 6,
        Vector16 = 7,
        Float16Buffer = 8,
        Float16 = 9,
        Float64 = 10,
        Int64 = 11,
        Int64Atomics = 12,
        ImageBasic = 13,
        ImageReadWrite = 14,
        ImageMipmap = 15,
        Pipes = 17,
        Groups = 18,
        DeviceEnqueue = 19,
        LiteralSampler = 20,
        AtomicStorage = 21,
        Int16 = 22,
        TessellationPointSize = 23,
        GeometryPointSize = 24,
        ImageGatherExtended = 25,
        StorageImageMultisample = 27,
        UniformBufferArrayDynamicIndexing = 28,
        SampledImageArrayDynamicIndexing = 29,
        StorageBufferArrayDynamicIndexing = 30,
        StorageImageArrayDynamicIndexing = 31,
        ClipDistance = 32,
        CullDistance = 33,
        ImageCubeArray = 34,
        SampleRateShading = 35,
        ImageRect = 36,
        SampledRect = 37,
        GenericPointer = 38,
        Int8 = 39,
        InputAttachment = 40,
        SparseResidency = 41,
        MinLod = 42,
        Sampled1D = 43,
        Image1D = 44,
        SampledCubeArray = 45,
        SampledBuffer = 46,
        ImageBuffer = 47,
        ImageMSArray = 48,
        StorageImageExtendedFormats = 49,
        ImageQuery = 50,
        DerivativeControl = 51,
        InterpolationFunction = 52,
        TransformFeedback = 53,
        GeometryStreams = 54,
        StorageImageReadWithoutFormat = 55,
        StorageImageWriteWithoutFormat = 56,
        MultiViewport = 57,
        SubgroupDispatch = 58,
        NamedBarrier = 59,
        PipeStorage = 60,
        GroupNonUniform = 61,
        GroupNonUniformVote = 62,
        GroupNonUniformArithmetic = 63,
        GroupNonUniformBallot = 64,
        GroupNonUniformShuffle = 65,
        GroupNonUniformShuffleRelative = 66,
        GroupNonUniformClustered = 67,
        GroupNonUniformQuad = 68,
        ShaderLayer = 69,
        ShaderViewportIndex = 70,
        FragmentShadingRateKHR = 4422,
        SubgroupBallotKHR = 4423,
        DrawParameters = 4427,
        SubgroupVoteKHR = 4431,
        StorageBuffer16BitAccess = 4433,
        StorageUniformBufferBlock16 = 4433,
        StorageUniform16 = 4434,
        UniformAndStorageBuffer16BitAccess = 4434,
        StoragePushConstant16 = 4435,
        StorageInputOutput16 = 4436,
        DeviceGroup = 4437,
        MultiView = 4439,
        VariablePointersStorageBuffer = 4441,
        VariablePointers = 4442,
        AtomicStorageOps = 4445,
        SampleMaskPostDepthCoverage = 4447,
        StorageBuffer8BitAccess = 4448,
        UniformAndStorageBuffer8BitAccess = 4449,
        StoragePushConstant8 = 4450,
        DenormPreserve = 4464,
        DenormFlushToZero = 4465,
        SignedZeroInfNanPreserve = 4466,
        RoundingModeRTE = 4467,
        RoundingModeRTZ = 4468,
        RayQueryProvisionalKHR = 4471,
        RayQueryKHR = 4472,
        RayTraversalPrimitiveCullingKHR = 4478,
        RayTracingKHR = 4479,
        Float16ImageAMD = 5008,
        ImageGatherBiasLodAMD = 5009,
        FragmentMaskAMD = 5010,
        StencilExportEXT = 5013,
        ImageReadWriteLodAMD = 5015,
        Int64ImageEXT = 5016,
        ShaderClockKHR = 5055,
        SampleMaskOverrideCoverageNV = 5249,
        GeometryShaderPassthroughNV = 5251,
        ShaderViewportIndexLayerEXT = 5254,
        ShaderViewportIndexLayerNV = 5254,
        ShaderViewportMaskNV = 5255,
        ShaderStereoViewNV = 5259,
        PerViewAttributesNV = 5260,
        FragmentFullyCoveredEXT = 5265,
        MeshShadingNV = 5266,
        ImageFootprintNV = 5282,
        FragmentBarycentricNV = 5284,
        ComputeDerivativeGroupQuadsNV = 5288,
        FragmentDensityEXT = 5291,
        ShadingRateNV = 5291,
        GroupNonUniformPartitionedNV = 5297,
        ShaderNonUniform = 5301,
        ShaderNonUniformEXT = 5301,
        RuntimeDescriptorArray = 5302,
        RuntimeDescriptorArrayEXT = 5302,
        InputAttachmentArrayDynamicIndexing = 5303,
        InputAttachmentArrayDynamicIndexingEXT = 5303,
        UniformTexelBufferArrayDynamicIndexing = 5304,
        UniformTexelBufferArrayDynamicIndexingEXT = 5304,
        StorageTexelBufferArrayDynamicIndexing = 5305,
        StorageTexelBufferArrayDynamicIndexingEXT = 5305,
        UniformBufferArrayNonUniformIndexing = 5306,
        UniformBufferArrayNonUniformIndexingEXT = 5306,
        SampledImageArrayNonUniformIndexing = 5307,
        SampledImageArrayNonUniformIndexingEXT = 5307,
        StorageBufferArrayNonUniformIndexing = 5308,
        StorageBufferArrayNonUniformIndexingEXT = 5308,
        StorageImageArrayNonUniformIndexing = 5309,
        StorageImageArrayNonUniformIndexingEXT = 5309,
        InputAttachmentArrayNonUniformIndexing = 5310,
        InputAttachmentArrayNonUniformIndexingEXT = 5310,
        UniformTexelBufferArrayNonUniformIndexing = 5311,
        UniformTexelBufferArrayNonUniformIndexingEXT = 5311,
        StorageTexelBufferArrayNonUniformIndexing = 5312,
        StorageTexelBufferArrayNonUniformIndexingEXT = 5312,
        RayTracingNV = 5340,
        VulkanMemoryModel = 5345,
        VulkanMemoryModelKHR = 5345,
        VulkanMemoryModelDeviceScope = 5346,
        VulkanMemoryModelDeviceScopeKHR = 5346,
        PhysicalStorageBufferAddresses = 5347,
        PhysicalStorageBufferAddressesEXT = 5347,
        ComputeDerivativeGroupLinearNV = 5350,
        RayTracingProvisionalKHR = 5353,
        CooperativeMatrixNV = 5357,
        FragmentShaderSampleInterlockEXT = 5363,
        FragmentShaderShadingRateInterlockEXT = 5372,
        ShaderSMBuiltinsNV = 5373,
        FragmentShaderPixelInterlockEXT = 5378,
        DemoteToHelperInvocationEXT = 5379,
        SubgroupShuffleINTEL = 5568,
        SubgroupBufferBlockIOINTEL = 5569,
        SubgroupImageBlockIOINTEL = 5570,
        SubgroupImageMediaBlockIOINTEL = 5579,
        IntegerFunctions2INTEL = 5584,
        FunctionPointersINTEL = 5603,
        IndirectReferencesINTEL = 5604,
        SubgroupAvcMotionEstimationINTEL = 5696,
        SubgroupAvcMotionEstimationIntraINTEL = 5697,
        SubgroupAvcMotionEstimationChromaINTEL = 5698,
        FPGAMemoryAttributesINTEL = 5824,
        UnstructuredLoopControlsINTEL = 5886,
        FPGALoopControlsINTEL = 5888,
        KernelAttributesINTEL = 5892,
        FPGAKernelAttributesINTEL = 5897,
        BlockingPipesINTEL = 5945,
        FPGARegINTEL = 5948,
        AtomicFloat32AddEXT = 6033,
        AtomicFloat64AddEXT = 6034,
        Max = 2147483647,
    }

    public enum SpvRayFlagsShift
    {
        OpaqueKHRShift = 0,
        NoOpaqueKHRShift = 1,
        TerminateOnFirstHitKHRShift = 2,
        SkipClosestHitShaderKHRShift = 3,
        CullBackFacingTrianglesKHRShift = 4,
        CullFrontFacingTrianglesKHRShift = 5,
        CullOpaqueKHRShift = 6,
        CullNoOpaqueKHRShift = 7,
        SkipTrianglesKHRShift = 8,
        SkipAABBsKHRShift = 9,
        Max = 2147483647,
    }

    public enum SpvRayFlagsMask
    {
        None = 0,
        OpaqueKHRMask = 1,
        NoOpaqueKHRMask = 2,
        TerminateOnFirstHitKHRMask = 4,
        SkipClosestHitShaderKHRMask = 8,
        CullBackFacingTrianglesKHRMask = 16,
        CullFrontFacingTrianglesKHRMask = 32,
        CullOpaqueKHRMask = 64,
        CullNoOpaqueKHRMask = 128,
        SkipTrianglesKHRMask = 256,
        SkipAABBsKHRMask = 512,
    }

    public enum SpvRayQueryIntersection
    {
        RayQueryCandidateIntersectionKHR = 0,
        RayQueryCommittedIntersectionKHR = 1,
        Max = 2147483647,
    }

    public enum SpvRayQueryCommittedIntersectionType
    {
        RayQueryCommittedIntersectionNoneKHR = 0,
        RayQueryCommittedIntersectionTriangleKHR = 1,
        RayQueryCommittedIntersectionGeneratedKHR = 2,
        Max = 2147483647,
    }

    public enum SpvRayQueryCandidateIntersectionType
    {
        RayQueryCandidateIntersectionTriangleKHR = 0,
        RayQueryCandidateIntersectionAABBKHR = 1,
        Max = 2147483647,
    }

    public enum SpvFragmentShadingRateShift
    {
        Vertical2PixelsShift = 0,
        Vertical4PixelsShift = 1,
        Horizontal2PixelsShift = 2,
        Horizontal4PixelsShift = 3,
        Max = 2147483647,
    }

    public enum SpvFragmentShadingRateMask
    {
        None = 0,
        Vertical2PixelsMask = 1,
        Vertical4PixelsMask = 2,
        Horizontal2PixelsMask = 4,
        Horizontal4PixelsMask = 8,
    }

    public enum SpvOp
    {
        Nop = 0,
        Undef = 1,
        SourceContinued = 2,
        Source = 3,
        SourceExtension = 4,
        Name = 5,
        MemberName = 6,
        String = 7,
        Line = 8,
        Extension = 10,
        ExtInstImport = 11,
        ExtInst = 12,
        MemoryModel = 14,
        EntryPoint = 15,
        ExecutionMode = 16,
        Capability = 17,
        TypeVoid = 19,
        TypeBool = 20,
        TypeInt = 21,
        TypeFloat = 22,
        TypeVector = 23,
        TypeMatrix = 24,
        TypeImage = 25,
        TypeSampler = 26,
        TypeSampledImage = 27,
        TypeArray = 28,
        TypeRuntimeArray = 29,
        TypeStruct = 30,
        TypeOpaque = 31,
        TypePointer = 32,
        TypeFunction = 33,
        TypeEvent = 34,
        TypeDeviceEvent = 35,
        TypeReserveId = 36,
        TypeQueue = 37,
        TypePipe = 38,
        TypeForwardPointer = 39,
        ConstantTrue = 41,
        ConstantFalse = 42,
        Constant = 43,
        ConstantComposite = 44,
        ConstantSampler = 45,
        ConstantNull = 46,
        SpecConstantTrue = 48,
        SpecConstantFalse = 49,
        SpecConstant = 50,
        SpecConstantComposite = 51,
        SpecConstantOp = 52,
        Function = 54,
        FunctionParameter = 55,
        FunctionEnd = 56,
        FunctionCall = 57,
        Variable = 59,
        ImageTexelPointer = 60,
        Load = 61,
        Store = 62,
        CopyMemory = 63,
        CopyMemorySized = 64,
        AccessChain = 65,
        InBoundsAccessChain = 66,
        PtrAccessChain = 67,
        ArrayLength = 68,
        GenericPtrMemSemantics = 69,
        InBoundsPtrAccessChain = 70,
        Decorate = 71,
        MemberDecorate = 72,
        DecorationGroup = 73,
        GroupDecorate = 74,
        GroupMemberDecorate = 75,
        VectorExtractDynamic = 77,
        VectorInsertDynamic = 78,
        VectorShuffle = 79,
        CompositeConstruct = 80,
        CompositeExtract = 81,
        CompositeInsert = 82,
        CopyObject = 83,
        Transpose = 84,
        SampledImage = 86,
        ImageSampleImplicitLod = 87,
        ImageSampleExplicitLod = 88,
        ImageSampleDrefImplicitLod = 89,
        ImageSampleDrefExplicitLod = 90,
        ImageSampleProjImplicitLod = 91,
        ImageSampleProjExplicitLod = 92,
        ImageSampleProjDrefImplicitLod = 93,
        ImageSampleProjDrefExplicitLod = 94,
        ImageFetch = 95,
        ImageGather = 96,
        ImageDrefGather = 97,
        ImageRead = 98,
        ImageWrite = 99,
        Image = 100,
        ImageQueryFormat = 101,
        ImageQueryOrder = 102,
        ImageQuerySizeLod = 103,
        ImageQuerySize = 104,
        ImageQueryLod = 105,
        ImageQueryLevels = 106,
        ImageQuerySamples = 107,
        ConvertFToU = 109,
        ConvertFToS = 110,
        ConvertSToF = 111,
        ConvertUToF = 112,
        UConvert = 113,
        SConvert = 114,
        FConvert = 115,
        QuantizeToF16 = 116,
        ConvertPtrToU = 117,
        SatConvertSToU = 118,
        SatConvertUToS = 119,
        ConvertUToPtr = 120,
        PtrCastToGeneric = 121,
        GenericCastToPtr = 122,
        GenericCastToPtrExplicit = 123,
        Bitcast = 124,
        SNegate = 126,
        FNegate = 127,
        IAdd = 128,
        FAdd = 129,
        ISub = 130,
        FSub = 131,
        IMul = 132,
        FMul = 133,
        UDiv = 134,
        SDiv = 135,
        FDiv = 136,
        UMod = 137,
        SRem = 138,
        SMod = 139,
        FRem = 140,
        FMod = 141,
        VectorTimesScalar = 142,
        MatrixTimesScalar = 143,
        VectorTimesMatrix = 144,
        MatrixTimesVector = 145,
        MatrixTimesMatrix = 146,
        OuterProduct = 147,
        Dot = 148,
        IAddCarry = 149,
        ISubBorrow = 150,
        UMulExtended = 151,
        SMulExtended = 152,
        Any = 154,
        All = 155,
        IsNan = 156,
        IsInf = 157,
        IsFinite = 158,
        IsNormal = 159,
        SignBitSet = 160,
        LessOrGreater = 161,
        Ordered = 162,
        Unordered = 163,
        LogicalEqual = 164,
        LogicalNotEqual = 165,
        LogicalOr = 166,
        LogicalAnd = 167,
        LogicalNot = 168,
        Select = 169,
        IEqual = 170,
        INotEqual = 171,
        UGreaterThan = 172,
        SGreaterThan = 173,
        UGreaterThanEqual = 174,
        SGreaterThanEqual = 175,
        ULessThan = 176,
        SLessThan = 177,
        ULessThanEqual = 178,
        SLessThanEqual = 179,
        FOrdEqual = 180,
        FUnordEqual = 181,
        FOrdNotEqual = 182,
        FUnordNotEqual = 183,
        FOrdLessThan = 184,
        FUnordLessThan = 185,
        FOrdGreaterThan = 186,
        FUnordGreaterThan = 187,
        FOrdLessThanEqual = 188,
        FUnordLessThanEqual = 189,
        FOrdGreaterThanEqual = 190,
        FUnordGreaterThanEqual = 191,
        ShiftRightLogical = 194,
        ShiftRightArithmetic = 195,
        ShiftLeftLogical = 196,
        BitwiseOr = 197,
        BitwiseXor = 198,
        BitwiseAnd = 199,
        Not = 200,
        BitFieldInsert = 201,
        BitFieldSExtract = 202,
        BitFieldUExtract = 203,
        BitReverse = 204,
        BitCount = 205,
        DPdx = 207,
        DPdy = 208,
        Fwidth = 209,
        DPdxFine = 210,
        DPdyFine = 211,
        FwidthFine = 212,
        DPdxCoarse = 213,
        DPdyCoarse = 214,
        FwidthCoarse = 215,
        EmitVertex = 218,
        EndPrimitive = 219,
        EmitStreamVertex = 220,
        EndStreamPrimitive = 221,
        ControlBarrier = 224,
        MemoryBarrier = 225,
        AtomicLoad = 227,
        AtomicStore = 228,
        AtomicExchange = 229,
        AtomicCompareExchange = 230,
        AtomicCompareExchangeWeak = 231,
        AtomicIIncrement = 232,
        AtomicIDecrement = 233,
        AtomicIAdd = 234,
        AtomicISub = 235,
        AtomicSMin = 236,
        AtomicUMin = 237,
        AtomicSMax = 238,
        AtomicUMax = 239,
        AtomicAnd = 240,
        AtomicOr = 241,
        AtomicXor = 242,
        Phi = 245,
        LoopMerge = 246,
        SelectionMerge = 247,
        Label = 248,
        Branch = 249,
        BranchConditional = 250,
        Switch = 251,
        Kill = 252,
        Return = 253,
        ReturnValue = 254,
        Unreachable = 255,
        LifetimeStart = 256,
        LifetimeStop = 257,
        GroupAsyncCopy = 259,
        GroupWaitEvents = 260,
        GroupAll = 261,
        GroupAny = 262,
        GroupBroadcast = 263,
        GroupIAdd = 264,
        GroupFAdd = 265,
        GroupFMin = 266,
        GroupUMin = 267,
        GroupSMin = 268,
        GroupFMax = 269,
        GroupUMax = 270,
        GroupSMax = 271,
        ReadPipe = 274,
        WritePipe = 275,
        ReservedReadPipe = 276,
        ReservedWritePipe = 277,
        ReserveReadPipePackets = 278,
        ReserveWritePipePackets = 279,
        CommitReadPipe = 280,
        CommitWritePipe = 281,
        IsValidReserveId = 282,
        GetNumPipePackets = 283,
        GetMaxPipePackets = 284,
        GroupReserveReadPipePackets = 285,
        GroupReserveWritePipePackets = 286,
        GroupCommitReadPipe = 287,
        GroupCommitWritePipe = 288,
        EnqueueMarker = 291,
        EnqueueKernel = 292,
        GetKernelNDrangeSubGroupCount = 293,
        GetKernelNDrangeMaxSubGroupSize = 294,
        GetKernelWorkGroupSize = 295,
        GetKernelPreferredWorkGroupSizeMultiple = 296,
        RetainEvent = 297,
        ReleaseEvent = 298,
        CreateUserEvent = 299,
        IsValidEvent = 300,
        SetUserEventStatus = 301,
        CaptureEventProfilingInfo = 302,
        GetDefaultQueue = 303,
        BuildNDRange = 304,
        ImageSparseSampleImplicitLod = 305,
        ImageSparseSampleExplicitLod = 306,
        ImageSparseSampleDrefImplicitLod = 307,
        ImageSparseSampleDrefExplicitLod = 308,
        ImageSparseSampleProjImplicitLod = 309,
        ImageSparseSampleProjExplicitLod = 310,
        ImageSparseSampleProjDrefImplicitLod = 311,
        ImageSparseSampleProjDrefExplicitLod = 312,
        ImageSparseFetch = 313,
        ImageSparseGather = 314,
        ImageSparseDrefGather = 315,
        ImageSparseTexelsResident = 316,
        NoLine = 317,
        AtomicFlagTestAndSet = 318,
        AtomicFlagClear = 319,
        ImageSparseRead = 320,
        SizeOf = 321,
        TypePipeStorage = 322,
        ConstantPipeStorage = 323,
        CreatePipeFromPipeStorage = 324,
        GetKernelLocalSizeForSubgroupCount = 325,
        GetKernelMaxNumSubgroups = 326,
        TypeNamedBarrier = 327,
        NamedBarrierInitialize = 328,
        MemoryNamedBarrier = 329,
        ModuleProcessed = 330,
        ExecutionModeId = 331,
        DecorateId = 332,
        GroupNonUniformElect = 333,
        GroupNonUniformAll = 334,
        GroupNonUniformAny = 335,
        GroupNonUniformAllEqual = 336,
        GroupNonUniformBroadcast = 337,
        GroupNonUniformBroadcastFirst = 338,
        GroupNonUniformBallot = 339,
        GroupNonUniformInverseBallot = 340,
        GroupNonUniformBallotBitExtract = 341,
        GroupNonUniformBallotBitCount = 342,
        GroupNonUniformBallotFindLSB = 343,
        GroupNonUniformBallotFindMSB = 344,
        GroupNonUniformShuffle = 345,
        GroupNonUniformShuffleXor = 346,
        GroupNonUniformShuffleUp = 347,
        GroupNonUniformShuffleDown = 348,
        GroupNonUniformIAdd = 349,
        GroupNonUniformFAdd = 350,
        GroupNonUniformIMul = 351,
        GroupNonUniformFMul = 352,
        GroupNonUniformSMin = 353,
        GroupNonUniformUMin = 354,
        GroupNonUniformFMin = 355,
        GroupNonUniformSMax = 356,
        GroupNonUniformUMax = 357,
        GroupNonUniformFMax = 358,
        GroupNonUniformBitwiseAnd = 359,
        GroupNonUniformBitwiseOr = 360,
        GroupNonUniformBitwiseXor = 361,
        GroupNonUniformLogicalAnd = 362,
        GroupNonUniformLogicalOr = 363,
        GroupNonUniformLogicalXor = 364,
        GroupNonUniformQuadBroadcast = 365,
        GroupNonUniformQuadSwap = 366,
        CopyLogical = 400,
        PtrEqual = 401,
        PtrNotEqual = 402,
        PtrDiff = 403,
        TerminateInvocation = 4416,
        SubgroupBallotKHR = 4421,
        SubgroupFirstInvocationKHR = 4422,
        SubgroupAllKHR = 4428,
        SubgroupAnyKHR = 4429,
        SubgroupAllEqualKHR = 4430,
        SubgroupReadInvocationKHR = 4432,
        TraceRayKHR = 4445,
        ExecuteCallableKHR = 4446,
        ConvertUToAccelerationStructureKHR = 4447,
        IgnoreIntersectionKHR = 4448,
        TerminateRayKHR = 4449,
        TypeRayQueryKHR = 4472,
        RayQueryInitializeKHR = 4473,
        RayQueryTerminateKHR = 4474,
        RayQueryGenerateIntersectionKHR = 4475,
        RayQueryConfirmIntersectionKHR = 4476,
        RayQueryProceedKHR = 4477,
        RayQueryGetIntersectionTypeKHR = 4479,
        GroupIAddNonUniformAMD = 5000,
        GroupFAddNonUniformAMD = 5001,
        GroupFMinNonUniformAMD = 5002,
        GroupUMinNonUniformAMD = 5003,
        GroupSMinNonUniformAMD = 5004,
        GroupFMaxNonUniformAMD = 5005,
        GroupUMaxNonUniformAMD = 5006,
        GroupSMaxNonUniformAMD = 5007,
        FragmentMaskFetchAMD = 5011,
        FragmentFetchAMD = 5012,
        ReadClockKHR = 5056,
        ImageSampleFootprintNV = 5283,
        GroupNonUniformPartitionNV = 5296,
        WritePackedPrimitiveIndices4x8NV = 5299,
        ReportIntersectionKHR = 5334,
        ReportIntersectionNV = 5334,
        IgnoreIntersectionNV = 5335,
        TerminateRayNV = 5336,
        TraceNV = 5337,
        TypeAccelerationStructureKHR = 5341,
        TypeAccelerationStructureNV = 5341,
        ExecuteCallableNV = 5344,
        TypeCooperativeMatrixNV = 5358,
        CooperativeMatrixLoadNV = 5359,
        CooperativeMatrixStoreNV = 5360,
        CooperativeMatrixMulAddNV = 5361,
        CooperativeMatrixLengthNV = 5362,
        BeginInvocationInterlockEXT = 5364,
        EndInvocationInterlockEXT = 5365,
        DemoteToHelperInvocationEXT = 5380,
        IsHelperInvocationEXT = 5381,
        SubgroupShuffleINTEL = 5571,
        SubgroupShuffleDownINTEL = 5572,
        SubgroupShuffleUpINTEL = 5573,
        SubgroupShuffleXorINTEL = 5574,
        SubgroupBlockReadINTEL = 5575,
        SubgroupBlockWriteINTEL = 5576,
        SubgroupImageBlockReadINTEL = 5577,
        SubgroupImageBlockWriteINTEL = 5578,
        SubgroupImageMediaBlockReadINTEL = 5580,
        SubgroupImageMediaBlockWriteINTEL = 5581,
        UCountLeadingZerosINTEL = 5585,
        UCountTrailingZerosINTEL = 5586,
        AbsISubINTEL = 5587,
        AbsUSubINTEL = 5588,
        IAddSatINTEL = 5589,
        UAddSatINTEL = 5590,
        IAverageINTEL = 5591,
        UAverageINTEL = 5592,
        IAverageRoundedINTEL = 5593,
        UAverageRoundedINTEL = 5594,
        ISubSatINTEL = 5595,
        USubSatINTEL = 5596,
        IMul32x16INTEL = 5597,
        UMul32x16INTEL = 5598,
        FunctionPointerINTEL = 5600,
        FunctionPointerCallINTEL = 5601,
        DecorateString = 5632,
        DecorateStringGOOGLE = 5632,
        MemberDecorateString = 5633,
        MemberDecorateStringGOOGLE = 5633,
        VmeImageINTEL = 5699,
        TypeVmeImageINTEL = 5700,
        TypeAvcImePayloadINTEL = 5701,
        TypeAvcRefPayloadINTEL = 5702,
        TypeAvcSicPayloadINTEL = 5703,
        TypeAvcMcePayloadINTEL = 5704,
        TypeAvcMceResultINTEL = 5705,
        TypeAvcImeResultINTEL = 5706,
        TypeAvcImeResultSingleReferenceStreamoutINTEL = 5707,
        TypeAvcImeResultDualReferenceStreamoutINTEL = 5708,
        TypeAvcImeSingleReferenceStreaminINTEL = 5709,
        TypeAvcImeDualReferenceStreaminINTEL = 5710,
        TypeAvcRefResultINTEL = 5711,
        TypeAvcSicResultINTEL = 5712,
        SubgroupAvcMceGetDefaultInterBaseMultiReferencePenaltyINTEL = 5713,
        SubgroupAvcMceSetInterBaseMultiReferencePenaltyINTEL = 5714,
        SubgroupAvcMceGetDefaultInterShapePenaltyINTEL = 5715,
        SubgroupAvcMceSetInterShapePenaltyINTEL = 5716,
        SubgroupAvcMceGetDefaultInterDirectionPenaltyINTEL = 5717,
        SubgroupAvcMceSetInterDirectionPenaltyINTEL = 5718,
        SubgroupAvcMceGetDefaultIntraLumaShapePenaltyINTEL = 5719,
        SubgroupAvcMceGetDefaultInterMotionVectorCostTableINTEL = 5720,
        SubgroupAvcMceGetDefaultHighPenaltyCostTableINTEL = 5721,
        SubgroupAvcMceGetDefaultMediumPenaltyCostTableINTEL = 5722,
        SubgroupAvcMceGetDefaultLowPenaltyCostTableINTEL = 5723,
        SubgroupAvcMceSetMotionVectorCostFunctionINTEL = 5724,
        SubgroupAvcMceGetDefaultIntraLumaModePenaltyINTEL = 5725,
        SubgroupAvcMceGetDefaultNonDcLumaIntraPenaltyINTEL = 5726,
        SubgroupAvcMceGetDefaultIntraChromaModeBasePenaltyINTEL = 5727,
        SubgroupAvcMceSetAcOnlyHaarINTEL = 5728,
        SubgroupAvcMceSetSourceInterlacedFieldPolarityINTEL = 5729,
        SubgroupAvcMceSetSingleReferenceInterlacedFieldPolarityINTEL = 5730,
        SubgroupAvcMceSetDualReferenceInterlacedFieldPolaritiesINTEL = 5731,
        SubgroupAvcMceConvertToImePayloadINTEL = 5732,
        SubgroupAvcMceConvertToImeResultINTEL = 5733,
        SubgroupAvcMceConvertToRefPayloadINTEL = 5734,
        SubgroupAvcMceConvertToRefResultINTEL = 5735,
        SubgroupAvcMceConvertToSicPayloadINTEL = 5736,
        SubgroupAvcMceConvertToSicResultINTEL = 5737,
        SubgroupAvcMceGetMotionVectorsINTEL = 5738,
        SubgroupAvcMceGetInterDistortionsINTEL = 5739,
        SubgroupAvcMceGetBestInterDistortionsINTEL = 5740,
        SubgroupAvcMceGetInterMajorShapeINTEL = 5741,
        SubgroupAvcMceGetInterMinorShapeINTEL = 5742,
        SubgroupAvcMceGetInterDirectionsINTEL = 5743,
        SubgroupAvcMceGetInterMotionVectorCountINTEL = 5744,
        SubgroupAvcMceGetInterReferenceIdsINTEL = 5745,
        SubgroupAvcMceGetInterReferenceInterlacedFieldPolaritiesINTEL = 5746,
        SubgroupAvcImeInitializeINTEL = 5747,
        SubgroupAvcImeSetSingleReferenceINTEL = 5748,
        SubgroupAvcImeSetDualReferenceINTEL = 5749,
        SubgroupAvcImeRefWindowSizeINTEL = 5750,
        SubgroupAvcImeAdjustRefOffsetINTEL = 5751,
        SubgroupAvcImeConvertToMcePayloadINTEL = 5752,
        SubgroupAvcImeSetMaxMotionVectorCountINTEL = 5753,
        SubgroupAvcImeSetUnidirectionalMixDisableINTEL = 5754,
        SubgroupAvcImeSetEarlySearchTerminationThresholdINTEL = 5755,
        SubgroupAvcImeSetWeightedSadINTEL = 5756,
        SubgroupAvcImeEvaluateWithSingleReferenceINTEL = 5757,
        SubgroupAvcImeEvaluateWithDualReferenceINTEL = 5758,
        SubgroupAvcImeEvaluateWithSingleReferenceStreaminINTEL = 5759,
        SubgroupAvcImeEvaluateWithDualReferenceStreaminINTEL = 5760,
        SubgroupAvcImeEvaluateWithSingleReferenceStreamoutINTEL = 5761,
        SubgroupAvcImeEvaluateWithDualReferenceStreamoutINTEL = 5762,
        SubgroupAvcImeEvaluateWithSingleReferenceStreaminoutINTEL = 5763,
        SubgroupAvcImeEvaluateWithDualReferenceStreaminoutINTEL = 5764,
        SubgroupAvcImeConvertToMceResultINTEL = 5765,
        SubgroupAvcImeGetSingleReferenceStreaminINTEL = 5766,
        SubgroupAvcImeGetDualReferenceStreaminINTEL = 5767,
        SubgroupAvcImeStripSingleReferenceStreamoutINTEL = 5768,
        SubgroupAvcImeStripDualReferenceStreamoutINTEL = 5769,
        SubgroupAvcImeGetStreamoutSingleReferenceMajorShapeMotionVectorsINTEL = 5770,
        SubgroupAvcImeGetStreamoutSingleReferenceMajorShapeDistortionsINTEL = 5771,
        SubgroupAvcImeGetStreamoutSingleReferenceMajorShapeReferenceIdsINTEL = 5772,
        SubgroupAvcImeGetStreamoutDualReferenceMajorShapeMotionVectorsINTEL = 5773,
        SubgroupAvcImeGetStreamoutDualReferenceMajorShapeDistortionsINTEL = 5774,
        SubgroupAvcImeGetStreamoutDualReferenceMajorShapeReferenceIdsINTEL = 5775,
        SubgroupAvcImeGetBorderReachedINTEL = 5776,
        SubgroupAvcImeGetTruncatedSearchIndicationINTEL = 5777,
        SubgroupAvcImeGetUnidirectionalEarlySearchTerminationINTEL = 5778,
        SubgroupAvcImeGetWeightingPatternMinimumMotionVectorINTEL = 5779,
        SubgroupAvcImeGetWeightingPatternMinimumDistortionINTEL = 5780,
        SubgroupAvcFmeInitializeINTEL = 5781,
        SubgroupAvcBmeInitializeINTEL = 5782,
        SubgroupAvcRefConvertToMcePayloadINTEL = 5783,
        SubgroupAvcRefSetBidirectionalMixDisableINTEL = 5784,
        SubgroupAvcRefSetBilinearFilterEnableINTEL = 5785,
        SubgroupAvcRefEvaluateWithSingleReferenceINTEL = 5786,
        SubgroupAvcRefEvaluateWithDualReferenceINTEL = 5787,
        SubgroupAvcRefEvaluateWithMultiReferenceINTEL = 5788,
        SubgroupAvcRefEvaluateWithMultiReferenceInterlacedINTEL = 5789,
        SubgroupAvcRefConvertToMceResultINTEL = 5790,
        SubgroupAvcSicInitializeINTEL = 5791,
        SubgroupAvcSicConfigureSkcINTEL = 5792,
        SubgroupAvcSicConfigureIpeLumaINTEL = 5793,
        SubgroupAvcSicConfigureIpeLumaChromaINTEL = 5794,
        SubgroupAvcSicGetMotionVectorMaskINTEL = 5795,
        SubgroupAvcSicConvertToMcePayloadINTEL = 5796,
        SubgroupAvcSicSetIntraLumaShapePenaltyINTEL = 5797,
        SubgroupAvcSicSetIntraLumaModeCostFunctionINTEL = 5798,
        SubgroupAvcSicSetIntraChromaModeCostFunctionINTEL = 5799,
        SubgroupAvcSicSetBilinearFilterEnableINTEL = 5800,
        SubgroupAvcSicSetSkcForwardTransformEnableINTEL = 5801,
        SubgroupAvcSicSetBlockBasedRawSkipSadINTEL = 5802,
        SubgroupAvcSicEvaluateIpeINTEL = 5803,
        SubgroupAvcSicEvaluateWithSingleReferenceINTEL = 5804,
        SubgroupAvcSicEvaluateWithDualReferenceINTEL = 5805,
        SubgroupAvcSicEvaluateWithMultiReferenceINTEL = 5806,
        SubgroupAvcSicEvaluateWithMultiReferenceInterlacedINTEL = 5807,
        SubgroupAvcSicConvertToMceResultINTEL = 5808,
        SubgroupAvcSicGetIpeLumaShapeINTEL = 5809,
        SubgroupAvcSicGetBestIpeLumaDistortionINTEL = 5810,
        SubgroupAvcSicGetBestIpeChromaDistortionINTEL = 5811,
        SubgroupAvcSicGetPackedIpeLumaModesINTEL = 5812,
        SubgroupAvcSicGetIpeChromaModeINTEL = 5813,
        SubgroupAvcSicGetPackedSkcLumaCountThresholdINTEL = 5814,
        SubgroupAvcSicGetPackedSkcLumaSumThresholdINTEL = 5815,
        SubgroupAvcSicGetInterRawSadsINTEL = 5816,
        LoopControlINTEL = 5887,
        ReadPipeBlockingINTEL = 5946,
        WritePipeBlockingINTEL = 5947,
        FPGARegINTEL = 5949,
        RayQueryGetRayTMinKHR = 6016,
        RayQueryGetRayFlagsKHR = 6017,
        RayQueryGetIntersectionTKHR = 6018,
        RayQueryGetIntersectionInstanceCustomIndexKHR = 6019,
        RayQueryGetIntersectionInstanceIdKHR = 6020,
        RayQueryGetIntersectionInstanceShaderBindingTableRecordOffsetKHR = 6021,
        RayQueryGetIntersectionGeometryIndexKHR = 6022,
        RayQueryGetIntersectionPrimitiveIndexKHR = 6023,
        RayQueryGetIntersectionBarycentricsKHR = 6024,
        RayQueryGetIntersectionFrontFaceKHR = 6025,
        RayQueryGetIntersectionCandidateAABBOpaqueKHR = 6026,
        RayQueryGetIntersectionObjectRayDirectionKHR = 6027,
        RayQueryGetIntersectionObjectRayOriginKHR = 6028,
        RayQueryGetWorldRayDirectionKHR = 6029,
        RayQueryGetWorldRayOriginKHR = 6030,
        RayQueryGetIntersectionObjectToWorldKHR = 6031,
        RayQueryGetIntersectionWorldToObjectKHR = 6032,
        AtomicFAddEXT = 6035,
        Max = 2147483647,
    }

    public enum SpvcResult
    {
        SUCCESS = 0,
        ERRORINVALIDSPIRV = -1,
        ERRORUNSUPPORTEDSPIRV = -2,
        ERROROUTOFMEMORY = -3,
        ERRORINVALIDARGUMENT = -4,
        ERRORINTMAX = 2147483647,
    }

    public enum SpvcCaptureMode
    {
        Copy = 0,
        TakeOwnership = 1,
        IntMax = 2147483647,
    }

    public enum SpvcBackend
    {
        None = 0,
        Glsl = 1,
        Hlsl = 2,
        Msl = 3,
        Cpp = 4,
        Json = 5,
        IntMax = 2147483647,
    }

    public enum SpvcResourceType
    {
        Unknown = 0,
        UniformBuffer = 1,
        StorageBuffer = 2,
        StageInput = 3,
        StageOutput = 4,
        SubpassInput = 5,
        StorageImage = 6,
        SampledImage = 7,
        AtomicCounter = 8,
        PushConstant = 9,
        SeparateImage = 10,
        SeparateSamplers = 11,
        AccelerationStructure = 12,
        RayQuery = 13,
        IntMax = 2147483647,
    }

    public enum SpvcBasetype
    {
        Unknown = 0,
        Void = 1,
        Boolean = 2,
        Int8 = 3,
        Uint8 = 4,
        Int16 = 5,
        Uint16 = 6,
        Int32 = 7,
        Uint32 = 8,
        Int64 = 9,
        Uint64 = 10,
        AtomicCounter = 11,
        Fp16 = 12,
        Fp32 = 13,
        Fp64 = 14,
        Struct = 15,
        Image = 16,
        SampledImage = 17,
        Sampler = 18,
        AccelerationStructure = 19,
        IntMax = 2147483647,
    }

    public enum SpvcMslPlatform
    {
        Ios = 0,
        Macos = 1,
        MaxInt = 2147483647,
    }

    public enum SpvcMslIndexType
    {
        None = 0,
        Uint16 = 1,
        Uint32 = 2,
        MaxInt = 2147483647,
    }

    public enum SpvcMslVertexFormat
    {
        Other = 0,
        Uint8 = 1,
        Uint16 = 2,
        Any16 = 3,
        Any32 = 4,
        OTHER = Other,
        UINT8 = Uint8,
        UINT16 = Uint16,
        IntMax = 2147483647,
    }

    public enum SpvcMslShaderInputFormat
    {
        Other = 0,
        Uint8 = 1,
        Uint16 = 2,
        Any16 = 3,
        Any32 = 4,
        SPVCMSLVERTEXFORMATOTHER = Other,
        SPVCMSLVERTEXFORMATUINT8 = Uint8,
        SPVCMSLVERTEXFORMATUINT16 = Uint16,
        IntMax = 2147483647,
    }

    public enum SpvcMslSamplerCoord
    {
        Normalized = 0,
        Pixel = 1,
        INTMAX = 2147483647,
    }

    public enum SpvcMslSamplerFilter
    {
        Nearest = 0,
        Linear = 1,
        IntMax = 2147483647,
    }

    public enum SpvcMslSamplerMipFilter
    {
        None = 0,
        Nearest = 1,
        Linear = 2,
        IntMax = 2147483647,
    }

    public enum SpvcMslSamplerAddress
    {
        ClampToZero = 0,
        ClampToEdge = 1,
        ClampToBorder = 2,
        Repeat = 3,
        MirroredRepeat = 4,
        IntMax = 2147483647,
    }

    public enum SpvcMslSamplerCompareFunc
    {
        Never = 0,
        Less = 1,
        LessEqual = 2,
        Greater = 3,
        GreaterEqual = 4,
        Equal = 5,
        NotEqual = 6,
        Always = 7,
        IntMax = 2147483647,
    }

    public enum SpvcMslSamplerBorderColor
    {
        TransparentBlack = 0,
        OpaqueBlack = 1,
        OpaqueWhite = 2,
        IntMax = 2147483647,
    }

    public enum SpvcMslFormatResolution
    {
        FormatRes444 = 0,
        FormatRes422 = 1,
        FormatRes420 = 2,
        IntMax = 2147483647,
    }

    public enum SpvcMslChromaLocation
    {
        CositedEven = 0,
        Midpoint = 1,
        IntMax = 2147483647,
    }

    public enum SpvcMslComponentSwizzle
    {
        Identity = 0,
        Zero = 1,
        One = 2,
        R = 3,
        G = 4,
        B = 5,
        A = 6,
        IntMax = 2147483647,
    }

    public enum SpvcMslSamplerYcbcrModelConversion
    {
        RgbIdentity = 0,
        YcbcrIdentity = 1,
        YcbcrBt709 = 2,
        YcbcrBt601 = 3,
        YcbcrBt2020 = 4,
        IntMax = 2147483647,
    }

    public enum SpvcMslSamplerYcbcrRange
    {
        ItuFull = 0,
        ItuNarrow = 1,
        IntMax = 2147483647,
    }

    public enum SpvcHlslBindingFlagBits
    {
        AUTONONEBIT = 0,
        AUTOPUSHCONSTANTBIT = 1,
        AUTOCBVBIT = 2,
        AUTOSRVBIT = 4,
        AUTOUAVBIT = 8,
        AUTOSAMPLERBIT = 16,
        AUTOALL = 2147483647,
    }

    public enum SpvcCompilerOption
    {
        Unknown = 0,
        ForceTemporary = 16777217,
        FlattenMultidimensionalArrays = 16777218,
        FixupDepthConvention = 16777219,
        FlipVertexY = 16777220,
        GlslSupportNonzeroBaseInstance = 33554437,
        GlslSeparateShaderObjects = 33554438,
        GlslEnable420packExtension = 33554439,
        GlslVersion = 33554440,
        GlslEs = 33554441,
        GlslVulkanSemantics = 33554442,
        GlslEsDefaultFloatPrecisionHighp = 33554443,
        GlslEsDefaultIntPrecisionHighp = 33554444,
        HlslShaderModel = 67108877,
        HlslPointSizeCompat = 67108878,
        HlslPointCoordCompat = 67108879,
        HlslSupportNonzeroBaseVertexBaseInstance = 67108880,
        MslVersion = 134217745,
        MslTexelBufferTextureWidth = 134217746,
        MslAuxBufferIndex = 134217747,
        MslSwizzleBufferIndex = 134217747,
        MslIndirectParamsBufferIndex = 134217748,
        MslShaderOutputBufferIndex = 134217749,
        MslShaderPatchOutputBufferIndex = 134217750,
        MslShaderTessFactorOutputBufferIndex = 134217751,
        MslShaderInputWorkgroupIndex = 134217752,
        MslEnablePointSizeBuiltin = 134217753,
        MslDisableRasterization = 134217754,
        MslCaptureOutputToBuffer = 134217755,
        MslSwizzleTextureSamples = 134217756,
        MslPadFragmentOutputComponents = 134217757,
        MslTessDomainOriginLowerLeft = 134217758,
        MslPlatform = 134217759,
        MslArgumentBuffers = 134217760,
        GlslEmitPushConstantAsUniformBuffer = 33554465,
        MslTextureBufferNative = 134217762,
        GlslEmitUniformBufferAsPlainUniforms = 33554467,
        MslBufferSizeBufferIndex = 134217764,
        EmitLineDirectives = 16777253,
        MslMultiview = 134217766,
        MslViewMaskBufferIndex = 134217767,
        MslDeviceIndex = 134217768,
        MslViewIndexFromDeviceIndex = 134217769,
        MslDispatchBase = 134217770,
        MslDynamicOffsetsBufferIndex = 134217771,
        MslTexture1dAs2d = 134217772,
        MslEnableBaseIndexZero = 134217773,
        MslIosFramebufferFetchSubpass = 134217774,
        MslFramebufferFetchSubpass = 134217774,
        MslInvariantFpMath = 134217775,
        MslEmulateCubemapArray = 134217776,
        MslEnableDecorationBinding = 134217777,
        MslForceActiveArgumentBufferResources = 134217778,
        MslForceNativeArrays = 134217779,
        EnableStorageImageQualifierDeduction = 16777268,
        HlslForceStorageBufferAsUav = 67108917,
        ForceZeroInitializedVariables = 16777270,
        HlslNonwritableUavTextureAsSrv = 67108919,
        MslEnableFragOutputMask = 134217784,
        MslEnableFragDepthBuiltin = 134217785,
        MslEnableFragStencilRefBuiltin = 134217786,
        MslEnableClipDistanceUserVarying = 134217787,
        HlslEnable16bitTypes = 67108924,
        MslMultiPatchWorkgroup = 134217789,
        MslShaderInputBufferIndex = 134217790,
        MslShaderIndexBufferIndex = 134217791,
        MslVertexForTessellation = 134217792,
        MslVertexIndexType = 134217793,
        GlslForceFlattenedIoBlocks = 33554498,
        MslMultiviewLayeredRendering = 134217795,
        MslArrayedSubpassInput = 134217796,
        MslR32uiLinearTextureAlignment = 134217797,
        MslR32uiAlignmentConstantId = 134217798,
        HlslFlattenMatrixVertexInputSemantics = 67108935,
        MslIosUseSimdgroupFunctions = 134217800,
        MslEmulateSubgroups = 134217801,
        MslFixedSubgroupSize = 134217802,
        MslForceSampleRateShading = 134217803,
        IntMax = 2147483647,
    }
}